stages:
  - test
  - build
  - deploy


variables:
  IMAGE_NAME: registry.gitlab.com/verhovenskyivan/ci-cd-course
  IMAGE_TAG: latest
run_tests:
  stage: test
  image: python:3.9-slim-buster
  before_script:
    - apt-get update && apt-get install make
  script:
    - apt-get update -qy
    - apt-get install -y python3 python3-pip

build-image:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  stage: build
  before_script:
    - docker login registry.gitlab.com -u $REGISTRY_USER -p $REGISTRY_PASSWORD 
  script: 
    - docker build -t  $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG


deploying-app:
  stage: deploy
  before_script:
    - chmod 400 $SSH_PRIVATE_KEY
  script: 
    - ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY root@$DEPLOY_SERVER "
        docker login registry.gitlab.com -u $REGISTRY_USER -p $REGISTRY_PASSWORD &&
        docker run -d -p 5000:5000 --name verhovensky-app $IMAGE_NAME:$IMAGE_TAG"
